apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azure-disk
  azureDisk:
    diskName: pv-disk
    diskURI: https://pvctestcontainer.blob.core.windows.net/vhds/tauqeerstorage.vhd