apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-service
spec:
  serviceName: "statefulset-service"
  replicas: 5
  selector:
    matchLabels:
      app: statefulset-service
  template:
    metadata:
      labels:
        app: statefulset-service
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.4
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: pvc-storage
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: pvc-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "azure-disk"
      resources:
        requests:
          storage: 1Gi